# 192.168.137.1
# authentication REST API for authentication-only calls

## POST

### POST ​/auth​/login  
### redirect with login from role
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "role":"admin"
}

# account REST API for account-only calls

## POST

### POST ​/account
### add account to joget account list
POST http://localhost:4000/account
Content-Type: application/json

{
  "username": "phurk",
  "password": "phurk@123",
  "url": "http://phurkjoget/jw/home/",
  "role": "admin",
  "name":"phurkjoget"
}

## GET

### GET ​/account
### get information of all account to public server
GET http://localhost:4000/account?id=5f6d73f25b559328b473a0c3

## PUT

### PUT ​/account/{id}
### update account of specification account id to public server
PUT http://localhost:4000/account?id=5f6d73f25b559328b473a0c3
Content-Type: application/json

{
  "username": "phurk",
  "password": "phurk@123",
  "name": "joget",
  "url": "http://phurkjoget/jw/home/",
  "role": "user"
}

## DELETE

### DELETE ​/account/{id}
### delete account of specification account id to public server
DELETE http://localhost:4000/account?id=5f6d73f25b559328b473a0c3
Content-Type: application/json
